---
title: "Data memo & Approval"
author: "Junhua Tan"
date: "01/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Timeline
Proposed project timeline. When do you expect to have your dataset loaded into R? When do you expect to start your analysis?

2/7 - Load data

2/14 - Data cleaning

2/21 - EDA

2/28 - model building

3/6 - Rough Draft

3/13 - Presentation

## Data Overview
Simple overview of the dataset. What does the dataset document? How do you plan to collect it? (Is it a simple download, a webscrape, etc? Provide a formal citation.) How big is the dataset? What kinds of variables will you be dealing with? Any missingness? Do you need to join two or more sources of data together?

This data was published by UC Irvine Machine Learning Repository in 1988 for the purpose of training a  model in which predict the presence of heart disease in the patient(data source: Janosi A., Steinbrunn W., M.D. (2019). UCI Machine Learning Repository [https://archive.ics.uci.edu/ml/datasets/Heart+Disease]. Irvine, CA: University of California, School of Information and Computer Science.). With this information, the researchers hope to help doctors to quickly make quicker, better judgement and provide care needed for patients. The data folder contains 1 csv file with 303 instances of 75 attributes. However, for our purpose of this final project, I will use only a subset of 14 attributes like all published experiments with this dataset did. In the future I might also consider incorporating additional attributes to provide a better summary of the disease.

The subset with the 14 attributes are published on Kaggle for model building competition. To collect this data, I will simply download from the kaggle website where the csv version of the dataset is uploaded. At short glimpse, all variables are represented with integer types. However, there are some categorical variables such as sex, chest pain type, etc. that were using integers to represent their levels. The data has no missing values. If the 14 attributes or the instances are found to be insufficient, I might join with the original dataset published from the UC Irvine repository for more informations.  

## Potential research question
Description of potential research questions. Are they predictive or inferential? Are these questions best answered by a classification or regression-based approach? What is the response variable? Which variables do you suspect will be useful in modeling the response?

One potential research question is to find what are the physiological factors that can be indicative for presence of heart diseases. This will be reflective in level of significance in the prediction model. A classification approach will work best given our goal is to predict the response variable `ca`, which is the presence (1) or absence (0) of heart diseases in a patient given his/her physiological status. So far I suspect `cp` chest pain type, `thalach` maximum heart rate acheived, and `oldpeak` ST depression induced by exercise relation to at rest will be useful in modeling the response.

## Potential Data Issues
Any difficulties you may encounter along the way. Is the data collection mechanism complicated? Is there significant missingness in the data?

There should not be any complication in the data collection process given these data are avaliable online. By skimming through the datasets, most of the data is cleaned except some minor problems with the variable type. Because all the variables are of integer type but only some are continuous. During the data cleaning process, we should treat those variable that used integers to represent each of their level as factor instead of integers. The main focus of this final project will be the exploratory data analysis and the model. In the EDA, I will include graphics that demonstrated some important relationships between the predictor variables and the response. I will also use 1/3 of the data for cross-validation for checking model performance. 